name: pr_comment_test

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  comment:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest
    steps:
      - name: Create comments
        run: |
          cat << EOF > comments
          ## サービスごとの影響範囲の確認
          - [ ] A
          - [ ] B
          - [ ] C
          EOF

      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run:
          gh pr comment -F ./comments "${URL}"