name: pr_comment_test

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment@a35cf36e5301d70b76f316e867e7788a55a31dae
        with:
          issue-number: ${{github.event.pull_request.number}}
          body: |
            ## サービスごとの影響範囲の確認
            - [ ] A
            - [ ] B
            - [ ] C